# Generated by Django 3.1.2 on 2020-11-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=15)),
                ('car_number', models.CharField(max_length=20)),
                ('reg_city', models.CharField(max_length=50)),
            ],
        ),
    ]
